#!/usr/bin/env bash

# Create a build container
container=$(buildah from --name asciidoctor-pdf fedora)

# Installation dependencies (https://github.com/asciidoctor/asciidoctor-pdf#prerequisites)
buildah run $container dnf -y --setopt="tsflags=nodocs" install ruby liberation-sans-fonts python ghostscript

# Install asciidoctor-pdf
buildah run $container gem install --no-document --minimal-deps --clear-sources --pre asciidoctor-pdf concurrent-ruby coderay pygments.rb rouge
buildah run $container curl -o /usr/local/bin/optimize-pdf https://raw.githubusercontent.com/asciidoctor/asciidoctor-pdf/master/bin/optimize-pdf
buildah run $container chmod +x /usr/local/bin/optimize-pdf

buildah config --workingdir /data $container
buildah config --entrypoint '["/usr/local/bin/asciidoctor-pdf"]' $container

buildah config --created-by "Tinsjourney" $container
buildah config --author "tintin@gnali.org @tinsjourney" --label name=asciidoctor-pdf $container
buildah config --label run="podman run --rm --name asciidoctor -v \$(CURDIR):/data:rw,Z IMAGE main.adoc -o engagement-journal.pdf" $container

# Some cleaning
buildah run $container dnf clean all

# Finally saves the running container to an image
buildah commit --rm $container asciidoctor-pdf:$(date +%Y%m%d)

# Push images to external repository
buildah push asciidoctor-pdf:$(date +%Y%m%d) docker://quay.io/tinsjourney/asciidoctor-pdf:$(date +%Y%m%d)
buildah push asciidoctor-pdf:$(date +%Y%m%d) docker://docker.io/tinsjourney/asciidoctor-pdf:$(date +%Y%m%d)
buildah push asciidoctor-pdf:$(date +%Y%m%d) docker://docker.io/tinsjourney/asciidoctor-pdf:latest
